[2주차] 이유라 학습 PR 제출합니다.
COW-edu/COW-React-4 pull request #12
Opened 2024-10-04 07:52 UTC by yuraup

## ✅ 학습 내용 요약

React 동작 방식 JSX , state와 props

## 🤔 고민했던 부분

- State 와 Props를 배우는 이유에 대해 생각했다.
- 결론: 차이점에 주목하되, 둘의 실제 작동과 연관지어서 더 생각해보려고 노력했다.

## 🔊 도움이 필요한 부분
- State와 Props의 차이점에 대해 설명해달라는 질문을 받으면 어떤 식으로 대답해야 좋은 대답일지 고민됐습니다.

2024-10-06 16:08 UTC, keemsebin reviewed
js를 사용하는 프레임워크와 라이브러리가 다양한데, 왜 리액트를 공부하려는지에 대한 내용이 있으면 좋을 것 같아요. 

리액트를 공부하기 전에 리액트의 어떤 장점 때문에 리액트를 많이 사용하는지, 그렇다면 리액트의 단점은 무엇인지, 해당 단점들을 어떻게 커버할 수 있을 지 생각해보면 좋을 것 같아요. 수고하셨습니다.

2024-10-06 16:08 UTC, keemsebin commented on week02/이유라/[2주차]이유라.md
> +>   - 컴포넌트 내부에서 값의 업데이트가 가능하지만 **불변성을 유지**해 줘야 하기 때문에 `setState()` (클래스형 컴포넌트) `useSate()` (함수형 컴포넌트)를 사용한다. <br>
어떻게 불변성을 유지할까요?

2024-10-06 16:08 UTC, keemsebin commented on week02/이유라/[2주차]이유라.md
> +>   const [state, setState] = useState(초기값);
`setState`가 `useState` 내부의 최신 값을 어떻게 계속 확인할 수 있을까요?

2024-10-06 16:08 UTC, keemsebin commented on week02/이유라/[2주차]이유라.md
> +> State(상태)는 컴포넌트에서 변경 가능한 데이터를 다루기 위한 객체이다.
아무런 값을 설정하지 않았을 경우 초깃값은 무엇일까요??

2024-10-06 16:08 UTC, keemsebin commented on week02/이유라/[2주차]이유라.md
> +> - Babel이 JSX를 JS로 변환해 주기 때문에 브라우저가 JSX 코드를 이해하고 실행할 수 있다.
다음과 같은 코드가 바벨을 거쳐 변환이 되면 어떤 형태를 띄고 있을까요!

```
const hello = (
  <div>
    <span>Hello world</span>
  </div>
 );
```

2024-10-06 16:08 UTC, keemsebin commented on week02/이유라/[2주차]이유라.md
> +> - props는 읽기 전용이기 때문에,자식 컴포넌트는 props 값을 변경할 수 없다. 따라서 props 값을 변경하고 싶다면 props를 전달한 부모 컴포넌트에서 변경하거나 state를 이용해 변경해야 한다.
컴포넌트의 잘못된 구조로 
`A -> B -> C -> ... F` 와 같이 A에 존재하는 데이터를 F까지 넘겨야 하는 경우에도 props를 써야 할까요??

2024-10-06 16:08 UTC, keemsebin commented on week02/이유라/[2주차]이유라.md
> +>
리액트의 렌더링 조건으로는 또 어떤 것들이 있는지 공부해보시는 것도 좋을 것 같습니다.

2024-10-06 16:08 UTC, keemsebin commented on week02/이유라/[2주차]이유라.md
> +> - props는 읽기 전용이기 때문에,자식 컴포넌트는 props 값을 변경할 수 없다. 따라서 props 값을 변경하고 싶다면 props를 전달한 부모 컴포넌트에서 변경하거나 state를 이용해 변경해야 한다.
간혹 props에 `setState`를 넘겨주는 경우가 종종있습니다. 왜 해당 상황을 지양해야 할까요?

2024-10-06 16:08 UTC, keemsebin commented on week02/이유라/[2주차]이유라.md
> +> const ChildComponent  = (props) => {
실제 프로젝트를 돌렸을 때 문제 없었나요 ㅎㅎ

2024-10-07 00:37 UTC, swgvenghy requested changes
학습내용 확인 완료했습니다. 저희 리뷰 반영해주시고 답변 달아주세요!

2024-10-07 00:37 UTC, swgvenghy commented on week02/이유라/[2주차]이유라.md
> +>   - 컴포넌트 내부에서 값의 업데이트가 가능하지만 **불변성을 유지**해 줘야 하기 때문에 `setState()` (클래스형 컴포넌트) `useSate()` (함수형 컴포넌트)를 사용한다. <br>
`useSate` 부분 오타수정해주세요!

2024-10-07 00:37 UTC, swgvenghy commented on week02/이유라/[2주차]이유라.md
> +> 함수형 컴포넌트에서는 useSate라는 Hook으로 상태를 관리한다.
여기도 오타 수정 부탁드립니다!

클래스형 컴포넌트에서 사용 예시도 한 번 확인해보시면 좋을 것 같습니다!

2024-10-07 00:37 UTC, swgvenghy commented on week02/이유라/[2주차]이유라.md
> +> const ChildComponent  = (props) => {
위 리뷰를 확인하면서 함께 props에서 구조분해할당을 적용하는 방법에 대해서도 확인하면 좋을 것 같아요

2024-10-07 07:50 UTC, yuraup commented on week02/이유라/[2주차]이유라.md
> +>   - 컴포넌트 내부에서 값의 업데이트가 가능하지만 **불변성을 유지**해 줘야 하기 때문에 `setState()` (클래스형 컴포넌트) `useSate()` (함수형 컴포넌트)를 사용한다. <br>
추가로 공부한 내용을 새로 작성하겠습니다!

새로운 객체나 배열을 생성해서 상태를 업데이트할 수 있습니다. 
setState 함수는 인수로 새로운 값을 할당하여 이전 객체와 다른 참조 주소를 가집니다. 이를 통해 리액트는 이전 state와 새로운 state가 서로 다른 참조 주소를 가지고 있음을 인식하여, 변경된 값을 올바르게 변경합니다.
이 과정에서는 ...(스프레드 연산자)를 사용해 새로운 객체를 생성할 수 있습니다. 
제가 해당 과정을 이해할 수 있었던 예시 코드를 첨부했습니다.

`const arr = [1,2,3]
const [value,setValue] = useState(arr)

setValue([...value,4])
`
이처럼 스프레드 연산자를 통해 이전 값을 복사하고, 새로운 값을 추가할 수 있습니다.

혹은 map, filter 등의 배열 메서드를 사용해 새로운 배열을 생성하여 원본 배열을 유지하고, 리액트가 변화를 감지하게 할 수 있습니다. 혹은 불변성을 지원하는 라이브러리를 사용하는 방법도 있다고 합니다.

2024-10-07 08:00 UTC, yuraup commented on week02/이유라/[2주차]이유라.md
> +> const ChildComponent  = (props) => {
앗... 오타가 있었습니다. 수정했습니다. 감사합니다.

2024-10-08 07:28 UTC, yuraup commented on week02/이유라/[2주차]이유라.md
> +> - Babel이 JSX를 JS로 변환해 주기 때문에 브라우저가 JSX 코드를 이해하고 실행할 수 있다.
바벨로 코드를 변환해 보니 다음과 같았습니다.

``` 
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const element = /*#__PURE__*/_jsxs(React.Fragment, {
  children: [/*#__PURE__*/_jsx("div", {
    children: "Hello World"
  }), /*#__PURE__*/_jsx("div", {
    children: "Goodbye World"
  })]
});
```
바벨은 설정에 따라 최신 JS 문법을 그대로 유지하거나 필요한 부분만 변환합니다.
불필요한 변환을 피하기 위해 간혹 ES6 문법을 그대로 남기기도 합니다.

틀린 부분이 있다면 말씀 부탁드립니다..

2024-10-08 07:53 UTC, yuraup commented on week02/이유라/[2주차]이유라.md
> +> - props는 읽기 전용이기 때문에,자식 컴포넌트는 props 값을 변경할 수 없다. 따라서 props 값을 변경하고 싶다면 props를 전달한 부모 컴포넌트에서 변경하거나 state를 이용해 변경해야 한다.
관련 내용도 md 파일에 추가 작성했습니다. 감사합니다!

2024-10-08 13:55 UTC, yuraup commented on week02/이유라/[2주차]이유라.md
> +> const ChildComponent  = (props) => {
반영했습니다!

2024-10-10 05:35 UTC, keemsebin approved these changes
수고하셨습니다~!

2024-10-10 05:35 UTC, keemsebin commented on week02/이유라/todo/src/components/TodoWriting/TodoWriting.jsx
> +  const PlusTodo = () => {
`PlusTodo` `addTodo` 요 두가지 변수명이 사용할 때 헷갈릴 것 같아요. 
조금 더 상황에 맞는 변수명을 지어주면 좋을 것 같습니다.

2024-10-10 05:35 UTC, keemsebin commented on week02/이유라/todo/src/components/TodoWriting/TodoWriting.jsx
> +        className="TodoInput"
일관성 있는 css 네이밍도 지켜지면 좋을 것 같아요! 요건 그냥 무시하셔도 좋습니당

2024-10-10 05:39 UTC, swgvenghy approved these changes
고생하셨습니다!! 자바스크립트를 사용하면서도 타입을 챙기려는 것이 인상깊네요 고생하셨습니다!

2024-10-10 05:52 UTC, keemsebin commented on week02/이유라/todo/src/App.jsx
> +        <Route path="/" element={<Todo />} />
지금은 페이지가 단일페이지인데, Route를 설정하신 이유가 있으신가요??

2024-10-11 05:21 UTC, yuraup commented on week02/이유라/todo/src/App.jsx
> +        <Route path="/" element={<Todo />} />
굳이 싶긴 했지만... todo 외에 일기장 기능 같은 게 추가될 경우를 생각해서 사용했습니다! 
다음 과제부터는 필요할 경우 세션 때 알려주신 create browser router 사용해 보겠습니다.

2024-10-11 05:54 UTC, yuraup commented on week02/이유라/todo/src/components/TodoWriting/TodoWriting.jsx
> +        className="TodoInput"
[f25ddc5](https://github.com/COW-edu/COW-React-4/pull/12/commits/f25ddc50d5b43bead0cca7505fc711668be380af)

말씀하신 사항들 수정했습니다! 
변수명은 제가 잘 지은 건지 확신은 없지만 전보다 더 잘 알아볼 수 있도록 수정했습니다..!

2024-10-11 05:57 UTC, yuraup commented
수정사항들 반영했습니다. 
추가로 또 반영해야 할 것들이 있다면 말씀해주세요! 
감사합니다.

[f25ddc5](https://github.com/COW-edu/COW-React-4/pull/12/commits/f25ddc50d5b43bead0cca7505fc711668be380af)

2024-10-31 09:41 UTC, merged