[2주차] 이성진 학습 PR 제출합니다.
COW-edu/COW-React-4 pull request #13
Opened 2024-10-05 14:15 UTC by leesj0188

## ✅ 학습 내용 요약

- JSX의 문법과 Javascript와 다른점, 사용법과 state와 props를 직접 코딩해보면서 작동방식에 대해 공부하였습니다.

## 🤔 고민했던 부분

- props의 사용법에 있어 상위 컴포넌트와 하위 컴포넌트를 연결하는 부분에 있어 헷갈리는 부분이 있었으나 직접 코딩해 보니 알 수 있었습니다.

## 🔊 도움이 필요한 부분

- state가 불변성을 유지해야하는 이유가 궁금합니다. 검색을 해봤는데 이해가 안되네요..

2024-10-06 16:39 UTC, keemsebin reviewed
불변성과 관련해서는 `closer`에 대해 먼저 학습하고 `useState`가 어떻게 구현되어 있는지 공부해보시면 좋을 것 같습니다. 

수고하셨습니다.

2024-10-06 16:39 UTC, keemsebin commented on week02/이성진/[2주차] 이성진.md
> +1. **class 를 지정할 때 class 가 아닌 className을 사용해야 한다.**
왜 class를 쓰면 안될까요??

2024-10-06 16:39 UTC, keemsebin commented on week02/이성진/[2주차] 이성진.md
> +1. **JSX는 반드시 하나의 부모태그가 감싸는 형식이어야 한다**.
3번에 해당 하는 내용인가요?

2024-10-06 16:39 UTC, keemsebin commented on week02/이성진/[2주차] 이성진.md
> +    - JSX에서는 데이터가 객체로 전달되기 때문에 HTML 대신 **카멜 케이스** 네이밍 규칙을 사용한다. ex) **classname (x) className**
`데이터가 객체로 전달되기 때문에` 요 부분 부연설명 부탁드립니다!

2024-10-06 16:39 UTC, keemsebin commented on week02/이성진/[2주차] 이성진.md
> +- JSX 는 리액트로 프로젝트를 개발할 때 사용되는 문법이므로 공식적인 Javascript 문법은 아니다.
JSX가 자바스크립트 코드로 어떻게 변환될까요? JSX는 리액트에서만 사용할까요??

2024-10-06 16:39 UTC, keemsebin commented on week02/이성진/[2주차] 이성진.md
> +    let [a,b] = useState('명지대 국제 통상학과');
`useState`는 구조분해 할당을 통해, 현재 상태 값,상태를 업데이트하는 함수,초깃값을 표현합니다.

예시가 잘못된 것 같아요. 공식 문서 보고 학습하는걸 추천합니다. 읽어보시면 좋을 것 같아요.
https://ko.react.dev/reference/react/useState

2024-10-06 16:39 UTC, keemsebin commented on week02/이성진/[2주차] 이성진.md
> +- state 도 변수 선언과 마찬가지로 정보를 담는 객체이지만 변수와 달리, state는  stat값이 변경될 때 state가 포함된 html을 자동으로 렌더링을 리액트가 해준다.
오타가 있는 것 같아요.

2024-10-06 16:39 UTC, keemsebin commented on week02/이성진/[2주차] 이성진.md
> +- state 도 변수 선언과 마찬가지로 정보를 담는 객체이지만 변수와 달리, state는  stat값이 변경될 때 state가 포함된 html을 자동으로 렌더링을 리액트가 해준다.
리액트 렌더링 조건에 대해 어떤 것들이 있는지 공부해보면 좋을 것 같아요.

2024-10-06 16:39 UTC, keemsebin commented on week02/이성진/[2주차] 이성진.md
> +1. props 를 사용하기 위해선 상위 컴포넌트에서 연결할 하위 컴포넌트를 import 해서 연결한다.
`import`해서 사용하는 거 맞나요?

https://ko.react.dev/learn/passing-props-to-a-component

2024-10-06 16:39 UTC, keemsebin commented on week02/이성진/[2주차] 이성진.md
> +- 단방향 데이터 흐름으로 인해 데이터 추적이 쉬워지고 디버깅이 쉬워진다.
부모 자식 관계가 많아질수록 `props`를 사용하는 데 이점이 있을까요? 혹은 전달해야 하는 props가 많아질 경우는 어떻게 대처하는 것이 좋을까요?

2024-10-06 16:39 UTC, keemsebin commented on week02/이성진/[2주차] 이성진.md
> +function lsj() {
실제 프로젝트 실행하여 돌려보신걸까요?

2024-10-07 00:49 UTC, swgvenghy commented
> ## 🔊 도움이 필요한 부분
> * state가 불변성을 유지해야하는 이유가 궁금합니다. 검색을 해봤는데 이해가 안되네요..

- 참조비교라는 개념이 있습니다! 해당 개념에 대해 찾아보셔도 좋을 것 같아요!
- state의 불변성을 유지하지 않는다면 참조비교를 하는 리액트에서는 변화를 감지하지 못하고 같은 값으로 인식합니다. 
- setState를 사용하면 새로운 값을 할당하기에 기존 state와 다른 메모리 주소를 가지고 있을 것이고 변화한 값으로 반영이 됩니다.

2024-10-07 01:04 UTC, swgvenghy requested changes

2024-10-07 01:04 UTC, swgvenghy commented on week02/이성진/[2주차] 이성진.md
> +- state 는 props와 다르게 컴포넌트 내에서 데이터를 변경할 수 있으나, 직접적으로 변경하는 것이 아닌 함수를 이용해서 변경해야 한다.
함수를 이용해 변경하는 예시가 들어가있으면 좋겠습니다! 간단한 코드여도 좋아요!

2024-10-07 01:04 UTC, swgvenghy commented on week02/이성진/[2주차] 이성진.md
> +- 컴포넌트 간의 의존성이 낮아져 코드 수정이나 유지 보수가 쉬워진다.
props가 많아지거나 거쳐가는 중간 컴포넌트가 많아질 경우 유지보수차원에서 어려워질 수 있어요! Prop Drilling 저희가 세션 진행할 거지만 이번 기회에 간단하게 알아보는 것 또한 좋을 것 같네요!

2024-10-07 01:54 UTC, leesj0188 commented on week02/이성진/[2주차] 이성진.md
> +1. **class 를 지정할 때 class 가 아닌 className을 사용해야 한다.**
JSX에서는 class는 javascript 예약어이기 때문에 혼란을 피하기 위해 클래스를 지정해주기 위해서는 className을 사용합니다.

2024-10-08 05:42 UTC, swgvenghy requested changes
리뷰 답변달기 및 수정부탁드립니다

2024-10-08 05:42 UTC, swgvenghy commented on week02/이성진/todo/src/App.jsx
> +          onClick={()=> onDeleteBtn(todoItem.id)}
onDeleteBtn에 대한 기능이 구현되어있지 않아요! 필요에 의해 넣었다면 반드시 기능구현을 해주셔야합니다.

2024-10-08 05:42 UTC, swgvenghy commented on week02/이성진/todo/src/App.jsx
> +        {(event)=> setInputValue(event.target.value)}/>
```suggestion
        <input 
          className='input' 
          value={inputValue} 
          type="text" 
          placeholder='해야할 일을 입력하세요' 
          onChange={(event) => setInputValue(event.target.value)}/> 
```

해당 코드처럼 가독성을 챙기는 습관도 들이면 좋겠어요

2024-10-08 05:42 UTC, swgvenghy commented on week02/이성진/todo/src/component/TodoBoard.jsx
> +function TodoBoard(props){
```suggestion
function TodoBoard({todoList}){
```
props를 받고 사용하는 것 보단 구조분해할당을 사용하여 props에 대한 정확한 네이밍을 해주는 것이 좋아보입니다.

2024-10-08 05:42 UTC, swgvenghy commented on week02/이성진/todo/src/component/TodoItem.jsx
> +function TodoItem(props){
```suggestion
function TodoItem({todoItem}){
```

여기도 동일하게 구조분해할당을 사용하는 것이 좋아보여요

2024-10-09 09:29 UTC, leesj0188 commented on week02/이성진/todo/src/component/TodoBoard.jsx
> +function TodoBoard(props){
확인 했습니다!

2024-10-09 09:30 UTC, leesj0188 commented on week02/이성진/todo/src/App.jsx
> +          onClick={()=> onDeleteBtn(todoItem.id)}
onDeleteBtn에 대한 기능 구현을 하려고 했으나 추가하는 과정에서 동작 방식이 아직 이해가 되지 않아서 버튼만 넣었는데 나중에 구현하는 것으로 하고 일단은 지금은 빼겠습니다!

2024-10-09 09:55 UTC, leesj0188 commented on week02/이성진/todo/src/App.jsx
> +        {(event)=> setInputValue(event.target.value)}/>
수정하겠습니다!

2024-10-09 09:55 UTC, leesj0188 commented on week02/이성진/[2주차] 이성진.md
> +- state 는 props와 다르게 컴포넌트 내에서 데이터를 변경할 수 있으나, 직접적으로 변경하는 것이 아닌 함수를 이용해서 변경해야 한다.
추가해서 다시 커밋하겠습니다!

2024-10-09 09:56 UTC, leesj0188 commented on week02/이성진/[2주차] 이성진.md
> +- 컴포넌트 간의 의존성이 낮아져 코드 수정이나 유지 보수가 쉬워진다.
다시 알아보겠습니다!

2024-10-09 09:56 UTC, leesj0188 commented on week02/이성진/[2주차] 이성진.md
> +1. **JSX는 반드시 하나의 부모태그가 감싸는 형식이어야 한다**.
오타 수정하겠습니다!

2024-10-09 09:58 UTC, leesj0188 commented on week02/이성진/[2주차] 이성진.md
> +    - JSX에서는 데이터가 객체로 전달되기 때문에 HTML 대신 **카멜 케이스** 네이밍 규칙을 사용한다. ex) **classname (x) className**
알겠습니다!

2024-10-09 09:59 UTC, leesj0188 commented on week02/이성진/[2주차] 이성진.md
> +- state 도 변수 선언과 마찬가지로 정보를 담는 객체이지만 변수와 달리, state는  stat값이 변경될 때 state가 포함된 html을 자동으로 렌더링을 리액트가 해준다.
수정하겠습니다!

2024-10-09 10:19 UTC, leesj0188 commented on week02/이성진/[2주차] 이성진.md
> +function lsj() {
수정해서 실행해 보았습니다! 다시 올리겠습니다!

2024-10-09 10:20 UTC, leesj0188 commented on week02/이성진/[2주차] 이성진.md
> +- state 도 변수 선언과 마찬가지로 정보를 담는 객체이지만 변수와 달리, state는  stat값이 변경될 때 state가 포함된 html을 자동으로 렌더링을 리액트가 해준다.
확인했습니다!

2024-10-09 10:25 UTC, leesj0188 commented on week02/이성진/[2주차] 이성진.md
> +- 단방향 데이터 흐름으로 인해 데이터 추적이 쉬워지고 디버깅이 쉬워진다.
부모 자식 관계가 많아질수록 props를 사용하게 된다면 불필요한 컴포넌트에서도 props를 전달해야 하기 때문에 복잡성이 증가하고 어떤 데이터가 어떤 컴포넌트에 전달되는 지 파악하기 어려워 집니다. 따라서 props가 많아질 경우엔 구조 분해 할당을 이용해서 컴포넌트를 분해하여 필요한 데이터만 받을 수 있게 대처해야 합니다.

2024-10-09 10:34 UTC, leesj0188 commented on week02/이성진/[2주차] 이성진.md
> +- JSX 는 리액트로 프로젝트를 개발할 때 사용되는 문법이므로 공식적인 Javascript 문법은 아니다.
JSX 자체로는 브라우저가 인식할 수 없지만 리액트는 JSX문법을 React.createElement() 함수를  호출하여 자바스크립트 코드로 전환합니다.
JSX는 리액트 전용이 아니며 다른 라이브러리(preact 등) 에서 사용하 수 있지만 주로 리액트에서 사용됩니다.

2024-10-10 05:51 UTC, keemsebin commented on week02/이성진/todo/src/App.jsx
> +  const [todolist,setTodolist]=useState([])
전체적으로 일관성있게 카멜케이스 적용하면 좋을 것 같아요.

2024-10-10 10:12 UTC, swgvenghy commented on week02/이성진/[2주차] 이성진.md
> +1. **JSX는 반드시 하나의 부모태그가 감싸는 형식이어야 한다**.
[0d21772](https://github.com/COW-edu/COW-React-4/pull/13/commits/0d2177244b2f1882775f731ca277271fdf5d2ce7)

2024-10-10 10:39 UTC, ujinsim commented on week02/이성진/[2주차] 이성진.md
> +5.  **모든 프로퍼티의 표기는 CamelCase로 작성한다.**
다른 네이밍 규칙에는 어떤 것이 있을까요?? 
컴포넌트 명명 규칙은 무엇일까요 ?

2024-10-31 09:42 UTC, merged