[2주차] 최원빈 학습 PR 제출합니다.
COW-edu/COW-React-4 pull request #16
Opened 2024-10-08 14:35 UTC by ChoiTheCreator

## ✅ 학습 내용 요약
1. React Rendering 방식

	•	렌더링: React는 컴포넌트를 기반으로 동작하며, 각 컴포넌트는 UI의 일부를 정의합니다. 컴포넌트가 렌더링되면 그 내부의 JSX가 HTML로 변환되어 브라우저에 표시됩니다.
	•	가상 DOM: React는 변경 사항을 효율적으로 처리하기 위해 “가상 DOM”을 사용합니다. 상태(state)나 속성(props)이 변경되면 React는 가상 DOM에서 변경 사항을 감지하고, 실제 DOM에 최소한의 변경만 적용하여 성능을 최적화합니다.

2. State

	•	정의: state는 컴포넌트의 상태를 저장하는 객체입니다. 각 컴포넌트는 자신의 state를 가지고 있으며, 이는 동적으로 변경될 수 있습니다.
	•	변경: state는 직접 변경할 수 없고, 항상 setState 또는 useState와 같은 함수를 사용하여 업데이트해야 합니다. 이로 인해 React는 변경 사항을 감지하고 리렌더링할 수 있습니다.
	•	예제: 사용자 입력, API 응답 등의 동적인 데이터를 관리할 때 주로 사용됩니다.

3. Props

	•	정의: props는 부모 컴포넌트가 자식 컴포넌트에 데이터를 전달하는 방법입니다. props는 읽기 전용이며, 자식 컴포넌트에서 변경할 수 없습니다.
	•	사용법: 부모 컴포넌트에서 자식 컴포넌트를 렌더링할 때 속성으로 값을 전달합니다. 자식 컴포넌트는 이를 props로 받아서 사용합니다.
	•	예제: UI의 다양한 요소를 동적으로 만들기 위해 자주 사용됩니다. 예를 들어, 버튼의 텍스트, 이미지 URL 등을 props로 전달할 수 있습니다.

4. JSX

	•	정의: JSX는 JavaScript XML의 약자로, JavaScript 코드 안에서 HTML과 유사한 문법을 사용하여 UI를 정의할 수 있게 해주는 문법입니다.
	•	특징: JSX는 JavaScript 표현식을 포함할 수 있으며, 이를 통해 동적인 UI를 쉽게 생성할 수 있습니다. React는 JSX를 사용하여 컴포넌트를 정의하고 렌더링합니다.
	•	예제: <div>Hello, {name}!</div>와 같이 사용할 수 있으며, 이 경우 name 변수의 값이 화면에 표시됩니다.
## 🤔 고민했던 부분

- 학습/과제 진행 간 고민한 포인트가 있다면 적어주세요.
todo list를 리액트로 구현하는게 자연스럽지가 않았습니다.
또한, state props 중요한 문법을 글로만 익히기가 쉽지가 않았습니다.

- 고민을 어떻게 생각하고 이를 어떻게 해결하였는지에 대해서 공유해주세요.
그에따라 저는  간단한 블로그를 리액트로 제작하였습니다.

따라서 개념 정리할때도, 텍스트 + 코드를 함께 작성하려고 노력했습니다.
물론, 강의를 참고하여 하였기에 무척 수동적인 측면이 없지 않았으나,
여러 개념들과 함께 혼자 코드를 짜보니 상당히 흥미로웠습니다.

사실 코드를 짜면서 처음 리액트를 짜다보니 기존의 js코드를 짜는 방식에서 아직 잘 못 벗어난거 같다고 느꼈습니다.
그리하여 처음엔 Js파일로 todolist를 만들고, 그 이후 jsx파일로 변환하는 과정이 상당히 쉽지 않았습니다.
특히 {} 로 데이터 바인딩을 하는 과정이 자연스럽지가 않습니다.
5년 내내 = 로 데이터 바인딩을 하다보니, {}를 연속해서 쓸때 상당한 혼란이 왔습니다.

그래도 확실히 매력적인 언어다 라는것을 깨달았습니다.

- 도움이 필요한 부분이 없다면 **삭제** 해도 됩니다.

2024-10-10 03:53 UTC, swgvenghy requested changes
week02 / 최원빈 / md파일, 공부 폴더를 넣어주세요!
리뷰 반영 부탁드립니다.

2024-10-10 03:53 UTC, vcz-ruso commented on week02/최원빈.md
> +<img width="421" alt="스크린샷 2024-10-08 오후 10 49 53" src="https://github.com/user-attachments/assets/4ab7a660-8b45-41de-908b-af2ca5
이 부분 사진이 생략되어있습니다. 필요한경우 추가해주세요!

2024-10-10 03:53 UTC, vcz-ruso commented on week02/최원빈.md
> +0886d1">
불필요한 부분 삭제해주세요!

2024-10-10 03:53 UTC, vcz-ruso commented on week02/최원빈.md
> +1. 원하는 폴더를 만든 후 <cmd(우클릭) 터미널 열기>에 npx create-react-app name을 한다
최근 공식적으로 CRA를 통한 리액트 프로젝트 시작에 대한 유지보수를 중단한 상태입니다. vite를 통해 CRA를 대체하여 프로젝트를 시작하는 방법을 사람들이 많이 사용하고는 합니다! 기존에 카톡방에 올려드린 vite를 사용하여 리액트 프로젝트를 시작하는 방법에 대해서도 알아보면 좋을 것 같아요

2024-10-10 03:53 UTC, swgvenghy commented on week02/최원빈.md
> +4. likesFunction 이라는 함수는 likesChange라는 state 내부 함수의 값을 바꾸게 한다.
일반적으로 상태변경함수를 set~~으로 명시합니다. 이 부분 참고해주시고
왜 state를 직접 변경하지않고 state변경함수를 사용하여 state의 상태를 변경할까요?

2024-10-10 03:53 UTC, swgvenghy commented on week02/최원빈.md
> +자료형을 독립적인 복사를 할때 활용한다.
복사를 말할 때 얕은복사, 깊은복사를 이야기하곤 합니다. 해당 경우에는 어떤 복사일까요?

2024-10-10 03:53 UTC, swgvenghy commented on week02/최원빈/todoList/todolist/src/App.js
> +  return (
해당 부분을 몇가지 컴포넌트로 나눌 수 있을 것 같아요. 만약 나눈다면 어떻게 범위를 나누어 컴포넌트로 나누실건가요?

2024-10-10 07:04 UTC, keemsebin commented on week02/최원빈.md
> +JSX는 <div>, <h1>, <p> 등과 같은 HTML 태그를 사용할 수 있으며, JavaScript 표현식을 중괄호 {}을 넣어 동적으로 값을 삽입할 수 있다. 이를 데이터 바인딩이라 한다.
`<div>`, `<h1>` 태그들을 md파일에 작성하면, 브라우저에서 HTML 태그로 해석됩니다. 수정해주세요.

2024-10-10 07:06 UTC, keemsebin commented on week02/최원빈.md
> +### 실제 사용 예시
잘못 작성한 것 같네요. 다시 학습 후 수정해주세요.

https://ko.react.dev/reference/react/useState

2024-10-10 07:16 UTC, keemsebin reviewed
저번주차에 비해서 나아진 모습은 보이지만, 주어진 내용에 대해 학습하고 학습한 내용을 다른 사람들과 공유하기 위해 깔끔하게 정리하는 게 조금 더 필요할 것 같습니다. 

실습코드에 대해서는 학습이 조금 더 이뤄진 뒤, 작성하는 것도 좋을 것 같아요. 수고하셨습니다.

2024-10-10 07:16 UTC, keemsebin commented on week02/최원빈.md
> +## #1. 변수 문법이 있는데 굳이 state를 써야하는가?
관련해서는 `closer` 에 대해 공부해보는 것 추천드립니다.

2024-10-10 10:38 UTC, ujinsim commented on week02/최원빈.md
> +```
isLoggedIn이 null이면 어떻게 될까요??
렌더링이 되지 않게 하려면 어떻게 하는 게 좋을까요 ??

또한 조건부 렌더링 방법에는 어떤 것이 있을까 알아보면 좋을 것 같습니다!

2024-10-10 10:38 UTC, ujinsim commented on week02/최원빈.md
> +### 조건부 랜더링
렌더링 오타 수정 부탁드립니다 !

2024-10-10 10:38 UTC, ujinsim commented on week02/최원빈.md
> +자료형을 독립적인 복사를 할때 활용한다.
Javascript에서 concat, spread, push는 어떤 차이가 있을까요 ?

2024-10-10 10:38 UTC, ujinsim commented on week02/최원빈.md
> +  let [a, b] = useState('이제 활용해보자');
모두 let으로 선언하신 이유가 궁금합니다 !

2024-10-10 11:14 UTC, ChoiTheCreator commented on week02/최원빈.md
> +<img width="421" alt="스크린샷 2024-10-08 오후 10 49 53" src="https://github.com/user-attachments/assets/4ab7a660-8b45-41de-908b-af2ca5
dd025399136cea509b483c560b1e9c1ddf2d9dea

네 방금 수정했습니다 !!! 감사합니다!

2024-10-10 12:45 UTC, ChoiTheCreator commented on week02/최원빈.md
> +0886d1">
dd025399136cea509b483c560b1e9c1ddf2d9dea

네 삭제완료했습니다 감사합니다!!!

2024-10-10 13:01 UTC, ChoiTheCreator commented on week02/최원빈.md
> +4. likesFunction 이라는 함수는 likesChange라는 state 내부 함수의 값을 바꾸게 한다.
네 앞으로 상태변경함수 작명할때 set을 참고하겠습니다.

cosnt [arr,setArr] = ues
arr의 값도 바귀지않나요?


const copy = [,,,]
copy ==asdfasd
//////
setArr(copy)


clg (arr)

2024-10-10 13:07 UTC, ChoiTheCreator commented on week02/최원빈.md
> +4. likesFunction 이라는 함수는 likesChange라는 state 내부 함수의 값을 바꾸게 한다.
네 앞으로 작명할때 참고하겠습니다!

state 변경 함수를 활용하면, 상태가 변경 될때 이전 상태와 새로운 상태를 비교하여 변경된 부분만 업데이트하는 방식으로 구동되기에 성능적으로 이점이 있다고 생각합니다.
또한 상태 함수로 상태 변경의 추적이 쉬워집니다. (실제로 개발자 도구에서 상태 변경을 시작적으로 확인하는 과정)을 참고해서 코드를 짰습니다.
아직은 정확히 감을 못잡았으나, 리액트의 상태 변경 함수는 비동기적으로 작동한다고 알고있는데, 변경 후의 상태 파악이 좀 더 용이할것 같습니다.

2024-10-28 00:28 UTC, ChoiTheCreator commented on week02/최원빈.md
> +JSX는 <div>, <h1>, <p> 등과 같은 HTML 태그를 사용할 수 있으며, JavaScript 표현식을 중괄호 {}을 넣어 동적으로 값을 삽입할 수 있다. 이를 데이터 바인딩이라 한다.
네 인지했습니다! 다음 Pr부터는 고려하여 제출하겠습니다!

2024-10-28 00:29 UTC, ChoiTheCreator commented on week02/최원빈.md
> +### 실제 사용 예시
네 감사합니다. 참고해서 학습하겠습니다!

2024-10-28 00:29 UTC, ChoiTheCreator commented on week02/최원빈.md
> +## #1. 변수 문법이 있는데 굳이 state를 써야하는가?
인지했습니다! closer에 대해 공부해보겠습니다! 좋은 피드백 의견 감사합니다!!

2024-10-28 03:27 UTC, ChoiTheCreator commented on week02/최원빈.md
> +  let [a, b] = useState('이제 활용해보자');
이때 당시에는 강의에서 했던 방식으로 혼자 코드를 짜서 let으로 습관적으로 선언을 했던것 같습니다. 
하지만 불변성 원칙을 준수하기 위해서는 state의 대부분은 특별한 케이스가 아닌 이상, const로 선언하는 것이 맞다고 생각합니다.

좀 더 자세히 말하면
리액트는 상태가 변경될때, 변경된 것을 감지하기 위해 새로운 객체를 만들어 비교하는데, 이때 직접 비교를 한다면 수정 여부를 감지하기 어려워 리렌더링이 올바른 작동이 안될수 있습니다.
따라서 const를 활용하여 의도치 않은 수정을 방지할 수 있습니다.
재할당을 금지하며, 의도적으로 새로운 객체를 
아래와 같은 코드에서 방식을 정확히 보이는데,
const [user, setUser] = useState({ name: "Alice" });

// 잘못된 방식: 기존 객체 직접 수정
user.name = "Bob";
setUser(user); // 리액트가 변경을 감지하지 못할 수 있음

// 올바른 방식: 새로운 객체를 생성
setUser({ ...user, name: "Bob" });


이런식으로 직접 수정하는 방식보다 ...(split 연산자)를 활용한 shallow copy로 객체를 얇은 복사를 하여 새로운 객체를 만들어 상태를 업데이트 하는 방식을 강제할수 있습니다!

2024-10-28 03:36 UTC, ChoiTheCreator commented on week02/최원빈.md
> +자료형을 독립적인 복사를 할때 활용한다.
spread Operator을 활용한 복사는 얇은 복사입니다.
얇은 복사를 활용한 복사는 기존 객체의 동일한 속성을 갖지만, 다른 메모리 주소에 저장되어있습니다. (즉 다른 객체입니다.)
하지만 얇은 복사한 객체를 수정하면. 원본 배열 또한 반영됩니다.

코드로 보면,
const user = { name: "Alice", details: { age: 25 } };
const newUser = { ...user };

// details 객체는 참조를 공유
console.log(user.details === newUser.details); // true

// details 내부 값 수정
newUser.details.age = 30;
console.log(user.details.age); // 30 (원본 객체도 영향을 받음)

이런 형태로 원본배열에도 영향이 간다는것을 알수있습니다.

반면, 깊은 복사는 참조형 데이터까지 완전히 새로운 복사본을 만드는 것이고, 이것은 완전히 분리된 독립객체가 됩니다.
const user = { name: "Alice", details: { age: 25 } };
const newUser = JSON.parse(JSON.stringify(user));

// 완전히 독립된 객체
console.log(user.details === newUser.details); // false

// 복사본 수정
newUser.details.age = 30;
console.log(user.details.age); // 25 (원본은 영향을 받지 않음)

이때는 detail 속성 또한 다르며, 기존 배열 수정시, 영향을 받지 않습니다.

2024-10-28 03:44 UTC, ChoiTheCreator commented on week02/최원빈/todoList/todolist/src/App.js
> +  return (
기존의 방식은 하나의 컴포넌트에 다 코드를 집어넣었는데,
전 다시 짠다면 총 3가지의 컴포넌트로 나누고싶습니다.
1. App (최상위 컴포넌트, 전체적 구조 담당)
2. TodoInput(입력과 할일 추가 기능)
3. TodoList(할일 목록 표시와 삭제, 체크 토글 담당) 

총 3가지로 나눌수 있을 것 같습니다.

2024-10-28 06:05 UTC, swgvenghy commented on week02/최원빈/todoList/todolist/src/App.js
> +  return (
좋습니다! 하나에 모든 걸 다 넣는다는 생각 보다 언제든지 확장이 될 수 있다는 생각을 가지고 관심사나 기능에 따라 컴포넌트를 분리해두는 습관을 가지면 좋겠습니다!

2024-10-28 06:06 UTC, swgvenghy approved these changes
고생하셨어용

2024-10-28 06:57 UTC, ChoiTheCreator commented on week02/최원빈.md
> +### 조건부 랜더링
네 인지했습니다!

2024-10-28 07:22 UTC, ChoiTheCreator commented on week02/최원빈.md
> +```
삼항 연산자를 활용한 조건부 렌더링에서 false로 판단되어, please log in 이 렌더링 됩니다.

만약 null일때, false일때를 구분 짓고자 한다면, (jsx에서 null은 False 취급을 당하므로, 저 간단한 삼항연산자 하나로는 구분 불가)
{isLoggedin ? null : isLoggedin ? <welcome> : <plz log in> }

이런 형태로 쓸수있을 것 같습니다.

다른 조건부 렌더링의 방법으로는
&& 연산자를 활용하여, 앞 조건 && <h1> welcome </h1> 이런식으로 쓴다면, 앞 조건이 true일때만 렌더링이 되게 할 수도 있으며.

컴포넌트 내부 분기( if문)활용 을 해서 렌더링할 수 있습니다.
예를 들면 아래와 같은 Greeting이란 컴포넌트가 있을때,
function Greeting({ isLoggedIn }) {
  if (isLoggedIn === null) {
    return null; // 아무것도 렌더링하지 않음
  }

  if (isLoggedIn) {
    return <h1>Welcome back!</h1>;
  } else {
    return <h1>Please log in.</h1>;
  }
}

이런식으로 컴포넌트 내부에 조건문을 넣어 할수도 있을 것 같습니다.

더 나아가 만약 컴포넌트 내부에 또 컴포넌트를 넣어서 조건문을 할수도있겠다만, 이는 권장되지 않는 방법이라 합니다.

2024-10-31 09:41 UTC, merged